### ISSUE TITLE
Does not work with PDF exports

### ISSUE THREAD

**Issue by iamchathu** [codeclou/gitbook-plugin-advanced-emoji#1]
I tried his plugin and it looks promising. But when i try to export pdf with emojis it creates blank placeholders.

I tried epub also do not work emoji in them

**Comment by clouless** [comment]
do you use `ebook-convert` to generate pdfs?
I will have a look, but can't promise anything.

**Comment by iamchathu** [comment]
i use `gitbook pdf . ./mypdf.pdf` to generate pdf

**Comment by iamchathu** [comment]
gitbook pdf uses ebook-convert and it is installed in my system and working correctly and generate pdfs and epubs without errors. But when i add emoji it work great with gitbook serve and gitbook build and generate htmls with emojis without errors but pdfs and epubs doesn't work

**Comment by clouless** [comment]
I just published version `0.1.6` to npmjs, so soon you should be able to build PDFs with emojis.
Here is preview: https://github.com/codeclou/gitbook-plugin-advanced-emoji/tree/pdf-test-book

**Comment by iamchathu** [comment]
Thanks It's working for PDF and EPUB
